### ISSUE TITLE
Coordinate System and TowerSE

### ISSUE THREAD

**Issue by SamAct** [WISDEM/WISDEM#110]
The **csystem.py** defines inertialToWind which rotates inertial to wind-alinged coordinate system. **TowerSE** uses this through the **WindWaveDrag.py** as:

`windLoads = DirectionVector(inputs['windLoads_Px'], inputs['windLoads_Py'], inputs['windLoads_Pz']).inertialToWind(inputs['windLoads_beta']).windToYaw(inputs['yaw'])`

I think it's transforming between the defined structural coordinate system of tower and the direction of the wind. If I define the x-x and y-y axis of the tower to be something, I need to resolve the wind load from a 30 degree yaw error, for example, to bending about the structural axis in order to design the tower.  Is this what its is doing? Do we have this documented any where?

**Comment by gbarter** [comment]
Both the `windLoads_beta` and `yaw` angles perform the same rotation about the z-axis (see [csystem.py lines 246-306](https://github.com/WISDEM/WISDEM/blob/master/wisdem/commonse/csystem.py#L246-L306)).  In the case that your turbine analysis c.s. is not aligned with the incoming wind direction and there is further a yaw offset of the rotor, then both angles are necessary.  Otherwise, for the problem you described, I would suggest setting beta=0.0 and yaw=30.0.

**Comment by SamAct** [comment]
Beta is along the direction of incoming wind speed? Same as tilt? I need more clarity on the wind, rotor & turbine coordinate system, is it same as FAST?

**Comment by gbarter** [comment]
Apologies for the poor documentation.  We are actually kicking off a concerted documentation improvement push tomorrow.  Please see [this diagram](https://wisdem.github.io/CommonSE/csystem.html#inertial-and-wind-aligned).

Beta is the angle between your structural x-axis direction and the incoming wind direction.  We usually align the structural x axis with the wind direction so that beta is zero and yaw refers to the offset of the rotor thrust vector.

**Comment by SamAct** [comment]
Oh yea totally forgot about that link, thanks for reminding.  Closing this now.
