### ISSUE TITLE
Questions on TowerSoil & pyFrame3dd

### ISSUE THREAD

**Issue by SamAct** [WISDEM/WISDEM#115]
As a followup question to #106 the `towersoil `only works for monopile and not to load-based-foundation. In `TowerPreframe `(for land-based) the spring stiffness values are assumed to be `1e16` in all three directions and `k_monoplie` is used for monopile - is this in z direction? Does the source "**Design of structures and foundations for vibrating machines. Gulf Pub Co, 1979**." have any known limitations for land-based foundations? Any other foundation model available that i can look into?

What is the significance of `rigid` in class `frame3dd.ReactionData`? I don't see impacts on frequencies changing value to `1e10 ` . There may me an issue here as value if set to `1e16 `gives minor changes. Can you please explain what i am missing? Thank you

**Comment by gbarter** [comment]
The baseline Frame3DD allows for either "rigid" or "not-rigid" for all 6 DOFs at every reaction point.  The python wrapper WISDEM created around Frame3DD tried to add more capability by being able to specify a stiffness of the reaction if desired.  From an implementation point of view, we now have a "rigid" float value input such that when the user sets the Kx/y/z value to that float, then you recover the original Frame3DD behavior.  Otherwise you are inputting a stiffness value with units.  This was done in an attempt to do a quick spring-stiffness model for soils when using piles on offshore structures.  In practice, it doesn't work quite as well as hoped, so needs more fundamental attention.  You are correct that this was never implemented for traditional land-based foundations.
