### ISSUE TITLE
Issue on tutorial 4

### ISSUE THREAD

**Issue by benoitpaillard** [WISDEM/WISDEM#116]
Hi all, I'm getting the following error when trying to run the fourth tutorial, at the last cell:
`RuntimeError: TowerSE (tow): 'promotes' failed to find any matches for the following names or patterns: ['monopile'].`

I'm a bit lost here, I tried to track down how that monopile does not have its match while for instance foundation_height gives no issue. Any hint ?

Thanks

**Comment by gbarter** [comment]
I apologize for this.  Those tutorials are out-of-date with the code.  We are working on a complete overhaul to the documentation and examples that are tightly coupled with our test framework so that they never fall out of date.  In the meanwhile, I have fixed the issue on the "develop" branch.  Let me know if you are comfortable switching to using that branch, otherwise I will give you some instructions or simply update the "master"

**Comment by benoitpaillard** [comment]
Working great thanks !
