### ISSUE TITLE
Significance of Weldability in TowerSE

### ISSUE THREAD

**Issue by SamAct** [WISDEM/WISDEM#128]
I am trying to understand the significance of parameters `weldability `and `manufatureablity` in TowerSE in more general terms. I see they are dependent upon diameter `(d)` , thickness` (t) `and `min_d_to_t` ratios. The `weldability `should be less then **0** and `manufatureablity `should be greater then **0** for a tower. What does this mean for the tower. Does lower `weldability `mean its easier to weld the tower?

Can you explain what it means and why can these be important?

**Comment by gbarter** [comment]
The `weldability` and `manufacturability` constraints are essentially over-generalized, and perhaps over-eager, titles for simple constraints:

- Diameter to thickness ratio: There is no firm number that is the minimum here as it depends somewhat on technique, but at some value, you cannot roll steel that has too low of a D:t ratio.  It was labeled as `weldability` because of the difficulty in welding the seam after a sheet has been rolled.
- Taper ratio: Also related to the rolling process, a trapezoid that must be rolled into a tapered cylinder (frustum) cannot have too aggressive a taper because of the tooling challenges.

Note that these constraints have been more appropriately titled in a future branch of WISDEM as: `constr_d_to_t` and `constr_taper`.
