### ISSUE TITLE
WISDEM/ORBIT

### ISSUE THREAD

**Issue by pollinico** [WISDEM/WISDEM#248]
## Description
Not possible to load load_config

### Steps to reproduce issue
from wisdem.orbit import ProjectManager, load_config

### Current behavior
load_config not found

### Expected behavior  
The issue is in __init__.py of WISDEM/ORBIT. If you compare it with the original ORBIT repo in __init__.py there should be also: 
`from .config import load_config, save_config`

### Code versions
_List versions only if relevant_
- Python
- …

**Comment by gbarter** [comment]
I think the issue is a mismatch between the version of ORBIT you are looking at and what is embedded in WISDEM.  We sync up with the latest ORBIT `dev` versions periodically.  I just created a feature branch to pull in the latest changes.  This will make its way to WISDEM `develop` in another week or two and then into `master` in the next release (likely soon).

Eventually, when ORBIT development slows, and is fully featured for WISDEM's needs, we will simply have ORBIT as a library dependency, instead of an embedded copy within the WISDEM repo.
