### ISSUE TITLE
Lateral boundary issue in rotor diameter optimization

### ISSUE THREAD

**Issue by diegoscmo** [WISDEM/WISDEM#256]
## Description
Optimization for rotor diameter always finds the solution as the lower set boundary.

### Issue
Under gc_PoseOptimization.py, under set_design_variables there is an issue in this line:
"configuration.rotor_diameter_user", lower=rotorD_opt["minimum"], upper=rotorD_opt["minimum"], ref=1.0e2
Should be:
"configuration.rotor_diameter_user", lower=rotorD_opt["minimum"], upper=rotorD_opt["maximum"], ref=1.0e2

### PS
I understand I am not following the exact "Issue template". Since I don't have experience contributing to large codes on github, I thought would be best to report it here since it is just a small fix.

**Comment by gbarter** [comment]
Hello Diego,

Thank you for bringing this up.  We have stumbled on this bug too.  It is currently fixed in the `develop` [branch](https://github.com/WISDEM/WISDEM/blob/develop/wisdem/glue_code/gc_PoseOptimization.py#L341) and will be part of the core WISDEM distribution in the next release.

Cheers,
Garrett

**Comment by diegoscmo** [comment]
Hello Garrett,

I should've checked the develop too before suggesting! Thank you for the response.

Diego
