### ISSUE TITLE
Turbine Cost Scales Linearly With Shear Exponent

### ISSUE THREAD

**Issue by kilojoules** [WISDEM/WISDEM#30]
![figure_1](https://cloud.githubusercontent.com/assets/8032238/8969065/37d06c52-35fe-11e5-9699-8130b0a323c2.png)

The forecasted turbine cost scales linear with the shear exponent at a negative slope. This seems to be caused by automatic sizing of the drivetrain...

**Comment by dykesk** [comment]
this is due to how the shear exponent is transferred into the rotor and used to scale hub height wind speed to influence aero-loads which automatically (with DriveSE) size the drivetrain and affect the cost.  Need to adjust this relationship - wind speeds should be scaled outside of the rotor (so will involve a RotorSE change as well as a change to the overall WISDEM assembly)

**Comment by kilojoules** [comment]
@dykesk Here are the individual turbine cost scalings. Very tricky.
![shears](https://cloud.githubusercontent.com/assets/8032238/25866144/adbe402e-34b2-11e7-9bec-d1f8f1629232.png)

**Comment by SamAct** [comment]
Sorry to barge in here @kilojoules. If by 

> how the shear exponent is transferred into the rotor

Ms. @dykesk  means, that the shear exponent results in varying mean wind speed and wind directions later being the function of blade azimuth changing mean angle of attack on the each blade sections also varies- blade flap harmonics.
1P, 3P, 6P prominently affecting the blade fatigue loads and 2P to flap-wise loads. (Considering these effect on the tower can be minimised with the use of efficient control systems.)
Shouldn't one expect the effects on a rotor (cost) to be more variable with respect to wind shear and tower comparatively less affected?

**Comment by dykesk** [comment]
@kilojoules is this still an issue?  I see its under "Needs Review" at the moment; I'm assuming that means its been fixed or is no longer relevant
