### ISSUE TITLE
change the spar location

### ISSUE THREAD

**Issue by SeongwooCheon** [WISDEM/WISDEM#316]
I use rotation and offset_y_pa to define the spar location.
So I think that if I change the offset_y_pa as a design variable, spar location is changed.

but, the error like this occurs:
File "c:\users\chsu\wisdem\wisdem\rotorse\parametrize_rotor.py", line 284, in compute
    if web_name[i] == spar_fore_name and opt_fore and opt_rear:
IndexError: list index out of range

I wrote the code using the given code, can you check it? or How can I solve the error?
I attached related codes.

thank you

[Spar_loaction.zip](https://github.com/WISDEM/WISDEM/files/7066725/Spar_loaction.zip)

**Comment by ptrbortolotti** [comment]
Hi,
in parametrize_rotor.py you are looping over the composite layers <for i in range(self.n_layers):>, but then you use index i over the webs. I believe that you should be looping over the webs with <for i in range(self.n_webs)>
Once that is fixed, the code runs however into another issue down the road. In the file gc_PoseOptimization.py, the lower bounds on blade.opt_var.spar_fore_opt are larger than your upper bounds. This happens because you are multiplying a negative quantity by 0.7 (LB) and 1.3 (UB). You may want to rethink the definition of the bounds.
Good luck!
Pietro Bortolotti
