### ISSUE TITLE
Release of PyPI wheels

### ISSUE THREAD

**Issue by natalia-gutov** [WISDEM/WISDEM#450]
# Description of feature
Is there any pre-built wheel for this package on pypi, so that is installable from pip. 
Alternative, provide a instruction how to install packages required with conda without setting up a new venv.

**Comment by gbarter** [comment]
The installation instructions involve interfacing with the code and examples as we might most users fall into that category.  Nevertheless, WISDEM can be installed via PyPi or conda via:
`conda install -c conda-forge wisdem`
and
`pip install wisdem`
https://pypi.org/project/wisdem/
https://anaconda.org/conda-forge/wisdem

**Comment by ccoulombe** [comment]
@gbarter  The sdist on PyPI is missing the `meson.build` and `meson_options.txt` files

**Comment by gbarter** [comment]
That is super helpful feedback- thank you!

I have [added](https://github.com/WISDEM/WISDEM/commit/fe9e435dc1bfd8cbd19ccaee292921ebb94bc6aa) the meson files to the package data listing, so that they are grabbed in the next release.  I will work towards doing a minor release increment to clear up the PyPi issues.
