### ISSUE TITLE
Question about turbine design with WISDEM

### ISSUE THREAD

**Issue by DingZL1207** [WISDEM/WISDEM#466]
Hello! I would like to seek assistance regarding wind turbine design. Could you please guide me on how to design a wind turbine from scratch in WISDEM? My goal is to design a wind turbine in WISDEM and then simulate its operation in the Fars.farm module of OpenFAST. I would greatly appreciate your help!

**Comment by gbarter** [comment]
Please see the examples and documentation of WISDEM.  The examples build to `18_rotor_tower_monopile` which describes the full design optimization of a turbine.  However, it is often more stable and insightful to optimize the components one at a time to understand the proper design variables bounds and constraint values before trying to do everything all at once.

To use FAST.Farm, I would first start with [WEIS](https://github.com/WISDEM/WEIS) to generate an OpenFAST input deck using the same geometry input file that WISDEM uses.  WEIS has many more modeling options because OpenFAST has many modeling options, so it can take some time to learn the software.  Once you have an OpenFAST turbine model, you can use the OpenFAST and FAST.Farm documentation to run a full wind farm.
