### ISSUE TITLE
jacketSE

### ISSUE THREAD

**Issue by applejuice122** [WISDEM/WISDEM#503]
## Description
I’ve been using an internal case study of the jacket and I’ve found that it’s been optimised 50 times without finding the best advantage. Can you explain why? I would like to use it to optimize the 15MW jacket, I tried to use the parameters of the internal 15MW Fukio platform, this issue also arose, I would be grateful if you could give me guidance.

### Steps to reproduce issue
File “D:\WISDEM-3.13.0\WISDEM-3.13.0\examples\17_jacket\read_outputs.py”, line 3
def read_csv_file(file_path):
IndentationError: unexpected indent
This is python error message (using internal examples)

### Current behavior
…RuntimeWarning: C:\Users\11653\AppData\Roaming\Python\Python39\site-packages\scipy\optimize\_minpack_py.py:177
The number of calls to function has reached maxfev = 50.Iteration limit reached    (Exit mode 9)
            Current function value: 3.733220247591898
            Iterations: 1
            Function evaluations: 1
            Gradient evaluations: 1
Optimization FAILED.
Iteration limit reached

### Expected behavior
…

### Code versions
WISDEM-3.13.0
- Python
- …

**Comment by gbarter** [comment]
The optimization is not converging because you are only running one optimization iteration.  You should change [this line](https://github.com/WISDEM/WISDEM/blob/master/examples/17_jacket/analysis_options_jacket.yaml#L55) to be something more like 100 or 200.  I would also change the [tolerance value](https://github.com/WISDEM/WISDEM/blob/master/examples/17_jacket/analysis_options_jacket.yaml#L52) to something like `1e-5` or `1e-6`.  We set the starting values to make for quick code testing, but they should be modified for real design optimization studies.

The error you posted in is the file, `read_outputs.py`, which must be something you wrote as that is not a WISDEM file that I am aware of.

**Comment by applejuice122** [comment]
Sorry, I accidentally copied the python file I wrote for FAST. That doesn't have anything to do with it. Please ignore it. I modified "max_iter" to 20 according to your suggestion. In addition, I also modified the tol to 1e-5. But it still has an error message: "The number of calls to function has reached maxfev = 50". I would appreciate it if you could help me explain this information in detail.

**Comment by gbarter** [comment]
You can safely ignore that warning.  I believe that is either from a linear wave approximation or from some stress checks.  We have tried to suppress it, but haven't succeeded.  It is unrelated to the larger design optimization problem.
