### ISSUE TITLE
Fatigue checks for tower and monopile

### ISSUE THREAD

**Issue by hishamtariq19** [WISDEM/WISDEM#578]
I am trying to size the support structure (tower+monopile) of IEA-15MW-RWT for minimum structural mass. My questions are regarding the fatigue checks.

1.  If I specify the value of gamma_fatigue: (say 1.755), does WISDEM check for fatigue at different sections of tower and monopile?
2. I was going through utilization_constraints.py and there is a code for estimation fatigue damage for tower station (using Miner's rule). Is it possible to share the reference/document from which this method is adopted?

I am attaching the code as well:
"""estimate fatigue damage for tower station

    Parmeters
    ---------
    M_DEL : array_like(float) (N*m)
        damage equivalent moment at tower section
    N_DEL : array_like(int)
        corresponding number of cycles in lifetime
    d : array_like(float) (m)
        tower diameter at section
    t : array_like(float) (m)
        tower shell thickness at section
    m : int
        slope of S/N curve
    DC : float (N/mm**2)
        some max stress from a standard
    eta : float
        safety factor
    stress_factor : float
        load_factor * stress_concentration_factor
    weld_factor : bool
        if True include an empirical weld factor

    Returns
    -------
    damage : float
        damage from Miner's rule for this tower section
    """

    # convert to mm
    dvec = np.array(d) * 1e3
    tvec = np.array(t) * 1e3
    r = 0.5 * dvec

    nvec = len(d)
    damage = np.zeros(nvec)

    # initialize weld factor (added cubic spline around corner)
    if weld_factor:
        x1 = 24.0
        x2 = 26.0
        spline = CubicSplineSegment(x1, x2, 1.0, (25.0 / x2) ** 0.25, 0.0, 25.0**0.25 * -0.25 * x2**-1.25)
        weld = spline.eval(tvec)
        weld[tvec >= x2] = (25.0 / tvec[tvec >= x2]) ** 0.25
        weld[tvec <= x1] = 1.0
    else:
        weld = 1.0

    # stress
    I = np.pi * r**3 * tvec
    sigma = M_DEL * r / I * stress_factor * 1e3  # convert to N/mm^2

    # maximum allowed stress
    Smax = DC * weld / eta

    # number of cycles to failure
    Nf = (Smax / sigma) ** m

    # number of cycles for this load
    N1 = 2e6  # TODO: where does this come from?
    N = N_DEL / N1

    # damage
    damage = N / Nf

    return damage

**Comment by gbarter** [comment]
WISDEM is a steady-state code, so there is no straightforward way to calculate fatigue, where either a time-domain or frequency-domain analysis is required.  There have been previous users that calculated Damage Equivalent Loads in OpenFAST (or equivalent tool), and assuming they are frozen or at least insensitive to the tower design, brought them into a WISDEM optimization.  The code snippets you highlighted are remnants of that approach, but are otherwise unused by WISDEM.  Today, if you would like to truly account for fatigue in a tower design, we recommend using [WEIS](https://github.com/WISDEM/WEIS), which wraps WISDEM's design approach around OpenFAST time-domain analysis.

**Comment by hishamtariq19** [comment]
Thank you for the reponse.
